// Decoded ShredStream — gRPC contract (ShredStream.com).
//
// Streams pre-execution Solana transactions decoded from shreds. The request/response
// messages are the market-standard `shreder_binary` messages, byte-for-byte:
// an existing market-standard client only needs to change its endpoint.
//
// Subscription model: bidirectional stream. Send at least one request with a
// named-filter map; the server tags each response with the names of the
// filters that matched. The map can be replaced mid-stream (no reconnect, no
// gap). An empty map delivers nothing; a named but EMPTY filter matches
// everything.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: decoded.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DecodedShredStreamService_SubscribeDecodedTransactions_FullMethodName = "/shredstream.com.DecodedShredStreamService/SubscribeDecodedTransactions"
)

// DecodedShredStreamServiceClient is the client API for DecodedShredStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DecodedShredStreamServiceClient interface {
	SubscribeDecodedTransactions(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeBinaryTransactionsRequest, SubscribeBinaryTransactionsResponse], error)
}

type decodedShredStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDecodedShredStreamServiceClient(cc grpc.ClientConnInterface) DecodedShredStreamServiceClient {
	return &decodedShredStreamServiceClient{cc}
}

func (c *decodedShredStreamServiceClient) SubscribeDecodedTransactions(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeBinaryTransactionsRequest, SubscribeBinaryTransactionsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DecodedShredStreamService_ServiceDesc.Streams[0], DecodedShredStreamService_SubscribeDecodedTransactions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeBinaryTransactionsRequest, SubscribeBinaryTransactionsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DecodedShredStreamService_SubscribeDecodedTransactionsClient = grpc.BidiStreamingClient[SubscribeBinaryTransactionsRequest, SubscribeBinaryTransactionsResponse]

// DecodedShredStreamServiceServer is the server API for DecodedShredStreamService service.
// All implementations must embed UnimplementedDecodedShredStreamServiceServer
// for forward compatibility.
type DecodedShredStreamServiceServer interface {
	SubscribeDecodedTransactions(grpc.BidiStreamingServer[SubscribeBinaryTransactionsRequest, SubscribeBinaryTransactionsResponse]) error
	mustEmbedUnimplementedDecodedShredStreamServiceServer()
}

// UnimplementedDecodedShredStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDecodedShredStreamServiceServer struct{}

func (UnimplementedDecodedShredStreamServiceServer) SubscribeDecodedTransactions(grpc.BidiStreamingServer[SubscribeBinaryTransactionsRequest, SubscribeBinaryTransactionsResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeDecodedTransactions not implemented")
}
func (UnimplementedDecodedShredStreamServiceServer) mustEmbedUnimplementedDecodedShredStreamServiceServer() {
}
func (UnimplementedDecodedShredStreamServiceServer) testEmbeddedByValue() {}

// UnsafeDecodedShredStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DecodedShredStreamServiceServer will
// result in compilation errors.
type UnsafeDecodedShredStreamServiceServer interface {
	mustEmbedUnimplementedDecodedShredStreamServiceServer()
}

func RegisterDecodedShredStreamServiceServer(s grpc.ServiceRegistrar, srv DecodedShredStreamServiceServer) {
	// If the following call panics, it indicates UnimplementedDecodedShredStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DecodedShredStreamService_ServiceDesc, srv)
}

func _DecodedShredStreamService_SubscribeDecodedTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DecodedShredStreamServiceServer).SubscribeDecodedTransactions(&grpc.GenericServerStream[SubscribeBinaryTransactionsRequest, SubscribeBinaryTransactionsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DecodedShredStreamService_SubscribeDecodedTransactionsServer = grpc.BidiStreamingServer[SubscribeBinaryTransactionsRequest, SubscribeBinaryTransactionsResponse]

// DecodedShredStreamService_ServiceDesc is the grpc.ServiceDesc for DecodedShredStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DecodedShredStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shredstream.com.DecodedShredStreamService",
	HandlerType: (*DecodedShredStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeDecodedTransactions",
			Handler:       _DecodedShredStreamService_SubscribeDecodedTransactions_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "decoded.proto",
}
