// Decoded ShredStream — gRPC contract (ShredStream.com).
//
// Streams pre-execution Solana transactions decoded from shreds. The request/response
// messages are the market-standard `shreder_binary` messages, byte-for-byte:
// an existing market-standard client only needs to change its endpoint.
//
// Subscription model: bidirectional stream. Send at least one request with a
// named-filter map; the server tags each response with the names of the
// filters that matched. The map can be replaced mid-stream (no reconnect, no
// gap). An empty map delivers nothing; a named but EMPTY filter matches
// everything.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: decoded.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_decoded_proto protoreflect.FileDescriptor

const file_decoded_proto_rawDesc = "" +
	"\n" +
	"\rdecoded.proto\x12\x0fshredstream.com\x1a\x14shreder_binary.proto2\xa9\x01\n" +
	"\x19DecodedShredStreamService\x12\x8b\x01\n" +
	"\x1cSubscribeDecodedTransactions\x122.shreder_binary.SubscribeBinaryTransactionsRequest\x1a3.shreder_binary.SubscribeBinaryTransactionsResponse(\x010\x01b\x06proto3"

var file_decoded_proto_goTypes = []any{
	(*SubscribeBinaryTransactionsRequest)(nil),  // 0: shreder_binary.SubscribeBinaryTransactionsRequest
	(*SubscribeBinaryTransactionsResponse)(nil), // 1: shreder_binary.SubscribeBinaryTransactionsResponse
}
var file_decoded_proto_depIdxs = []int32{
	0, // 0: shredstream.com.DecodedShredStreamService.SubscribeDecodedTransactions:input_type -> shreder_binary.SubscribeBinaryTransactionsRequest
	1, // 1: shredstream.com.DecodedShredStreamService.SubscribeDecodedTransactions:output_type -> shreder_binary.SubscribeBinaryTransactionsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_decoded_proto_init() }
func file_decoded_proto_init() {
	if File_decoded_proto != nil {
		return
	}
	file_shreder_binary_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_decoded_proto_rawDesc), len(file_decoded_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_decoded_proto_goTypes,
		DependencyIndexes: file_decoded_proto_depIdxs,
	}.Build()
	File_decoded_proto = out.File
	file_decoded_proto_goTypes = nil
	file_decoded_proto_depIdxs = nil
}
