// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: shreder_binary.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeBinaryTransactionsRequest struct {
	state         protoimpl.MessageState                               `protogen:"open.v1"`
	Transactions  map[string]*SubscribeRequestFilterBinaryTransactions `protobuf:"bytes,3,rep,name=transactions,proto3" json:"transactions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeBinaryTransactionsRequest) Reset() {
	*x = SubscribeBinaryTransactionsRequest{}
	mi := &file_shreder_binary_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeBinaryTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeBinaryTransactionsRequest) ProtoMessage() {}

func (x *SubscribeBinaryTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shreder_binary_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeBinaryTransactionsRequest.ProtoReflect.Descriptor instead.
func (*SubscribeBinaryTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_shreder_binary_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeBinaryTransactionsRequest) GetTransactions() map[string]*SubscribeRequestFilterBinaryTransactions {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type SubscribeBinaryTransactionsResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Filters       []string                          `protobuf:"bytes,1,rep,name=filters,proto3" json:"filters,omitempty"`
	Transaction   *SubscribeUpdateBinaryTransaction `protobuf:"bytes,4,opt,name=transaction,proto3" json:"transaction,omitempty"`
	CreatedAt     *timestamppb.Timestamp            `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeBinaryTransactionsResponse) Reset() {
	*x = SubscribeBinaryTransactionsResponse{}
	mi := &file_shreder_binary_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeBinaryTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeBinaryTransactionsResponse) ProtoMessage() {}

func (x *SubscribeBinaryTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shreder_binary_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeBinaryTransactionsResponse.ProtoReflect.Descriptor instead.
func (*SubscribeBinaryTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_shreder_binary_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeBinaryTransactionsResponse) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SubscribeBinaryTransactionsResponse) GetTransaction() *SubscribeUpdateBinaryTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *SubscribeBinaryTransactionsResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SubscribeUpdateBinaryTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *BinaryTransaction     `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	Slot          uint64                 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeUpdateBinaryTransaction) Reset() {
	*x = SubscribeUpdateBinaryTransaction{}
	mi := &file_shreder_binary_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeUpdateBinaryTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeUpdateBinaryTransaction) ProtoMessage() {}

func (x *SubscribeUpdateBinaryTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_shreder_binary_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeUpdateBinaryTransaction.ProtoReflect.Descriptor instead.
func (*SubscribeUpdateBinaryTransaction) Descriptor() ([]byte, []int) {
	return file_shreder_binary_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeUpdateBinaryTransaction) GetTransaction() *BinaryTransaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

func (x *SubscribeUpdateBinaryTransaction) GetSlot() uint64 {
	if x != nil {
		return x.Slot
	}
	return 0
}

type SubscribeRequestFilterBinaryTransactions struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccountInclude  []string               `protobuf:"bytes,3,rep,name=account_include,json=accountInclude,proto3" json:"account_include,omitempty"`
	AccountExclude  []string               `protobuf:"bytes,4,rep,name=account_exclude,json=accountExclude,proto3" json:"account_exclude,omitempty"`
	AccountRequired []string               `protobuf:"bytes,6,rep,name=account_required,json=accountRequired,proto3" json:"account_required,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubscribeRequestFilterBinaryTransactions) Reset() {
	*x = SubscribeRequestFilterBinaryTransactions{}
	mi := &file_shreder_binary_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequestFilterBinaryTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequestFilterBinaryTransactions) ProtoMessage() {}

func (x *SubscribeRequestFilterBinaryTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_shreder_binary_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequestFilterBinaryTransactions.ProtoReflect.Descriptor instead.
func (*SubscribeRequestFilterBinaryTransactions) Descriptor() ([]byte, []int) {
	return file_shreder_binary_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeRequestFilterBinaryTransactions) GetAccountInclude() []string {
	if x != nil {
		return x.AccountInclude
	}
	return nil
}

func (x *SubscribeRequestFilterBinaryTransactions) GetAccountExclude() []string {
	if x != nil {
		return x.AccountExclude
	}
	return nil
}

func (x *SubscribeRequestFilterBinaryTransactions) GetAccountRequired() []string {
	if x != nil {
		return x.AccountRequired
	}
	return nil
}

type BinaryTransaction struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Signatures [][]byte               `protobuf:"bytes,1,rep,name=signatures,proto3" json:"signatures,omitempty"`
	// Serialized bytes of VersionedTransaction: https://docs.rs/solana-transaction/3.0.2/solana_transaction/versioned/struct.VersionedTransaction.html
	BinaryTransaction []byte `protobuf:"bytes,3,opt,name=binary_transaction,json=binaryTransaction,proto3" json:"binary_transaction,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BinaryTransaction) Reset() {
	*x = BinaryTransaction{}
	mi := &file_shreder_binary_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryTransaction) ProtoMessage() {}

func (x *BinaryTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_shreder_binary_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BinaryTransaction.ProtoReflect.Descriptor instead.
func (*BinaryTransaction) Descriptor() ([]byte, []int) {
	return file_shreder_binary_proto_rawDescGZIP(), []int{4}
}

func (x *BinaryTransaction) GetSignatures() [][]byte {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *BinaryTransaction) GetBinaryTransaction() []byte {
	if x != nil {
		return x.BinaryTransaction
	}
	return nil
}

var File_shreder_binary_proto protoreflect.FileDescriptor

const file_shreder_binary_proto_rawDesc = "" +
	"\n" +
	"\x14shreder_binary.proto\x12\x0eshreder_binary\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x02\n" +
	"\"SubscribeBinaryTransactionsRequest\x12h\n" +
	"\ftransactions\x18\x03 \x03(\v2D.shreder_binary.SubscribeBinaryTransactionsRequest.TransactionsEntryR\ftransactions\x1ay\n" +
	"\x11TransactionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12N\n" +
	"\x05value\x18\x02 \x01(\v28.shreder_binary.SubscribeRequestFilterBinaryTransactionsR\x05value:\x028\x01\"\xce\x01\n" +
	"#SubscribeBinaryTransactionsResponse\x12\x18\n" +
	"\afilters\x18\x01 \x03(\tR\afilters\x12R\n" +
	"\vtransaction\x18\x04 \x01(\v20.shreder_binary.SubscribeUpdateBinaryTransactionR\vtransaction\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"{\n" +
	" SubscribeUpdateBinaryTransaction\x12C\n" +
	"\vtransaction\x18\x01 \x01(\v2!.shreder_binary.BinaryTransactionR\vtransaction\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\x04R\x04slot\"\xa7\x01\n" +
	"(SubscribeRequestFilterBinaryTransactions\x12'\n" +
	"\x0faccount_include\x18\x03 \x03(\tR\x0eaccountInclude\x12'\n" +
	"\x0faccount_exclude\x18\x04 \x03(\tR\x0eaccountExclude\x12)\n" +
	"\x10account_required\x18\x06 \x03(\tR\x0faccountRequired\"b\n" +
	"\x11BinaryTransaction\x12\x1e\n" +
	"\n" +
	"signatures\x18\x01 \x03(\fR\n" +
	"signatures\x12-\n" +
	"\x12binary_transaction\x18\x03 \x01(\fR\x11binaryTransaction2\xa3\x01\n" +
	"\x14ShrederBinaryService\x12\x8a\x01\n" +
	"\x1bSubscribeBinaryTransactions\x122.shreder_binary.SubscribeBinaryTransactionsRequest\x1a3.shreder_binary.SubscribeBinaryTransactionsResponse(\x010\x01b\x06proto3"

var (
	file_shreder_binary_proto_rawDescOnce sync.Once
	file_shreder_binary_proto_rawDescData []byte
)

func file_shreder_binary_proto_rawDescGZIP() []byte {
	file_shreder_binary_proto_rawDescOnce.Do(func() {
		file_shreder_binary_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shreder_binary_proto_rawDesc), len(file_shreder_binary_proto_rawDesc)))
	})
	return file_shreder_binary_proto_rawDescData
}

var file_shreder_binary_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_shreder_binary_proto_goTypes = []any{
	(*SubscribeBinaryTransactionsRequest)(nil),       // 0: shreder_binary.SubscribeBinaryTransactionsRequest
	(*SubscribeBinaryTransactionsResponse)(nil),      // 1: shreder_binary.SubscribeBinaryTransactionsResponse
	(*SubscribeUpdateBinaryTransaction)(nil),         // 2: shreder_binary.SubscribeUpdateBinaryTransaction
	(*SubscribeRequestFilterBinaryTransactions)(nil), // 3: shreder_binary.SubscribeRequestFilterBinaryTransactions
	(*BinaryTransaction)(nil),                        // 4: shreder_binary.BinaryTransaction
	nil,                                              // 5: shreder_binary.SubscribeBinaryTransactionsRequest.TransactionsEntry
	(*timestamppb.Timestamp)(nil),                    // 6: google.protobuf.Timestamp
}
var file_shreder_binary_proto_depIdxs = []int32{
	5, // 0: shreder_binary.SubscribeBinaryTransactionsRequest.transactions:type_name -> shreder_binary.SubscribeBinaryTransactionsRequest.TransactionsEntry
	2, // 1: shreder_binary.SubscribeBinaryTransactionsResponse.transaction:type_name -> shreder_binary.SubscribeUpdateBinaryTransaction
	6, // 2: shreder_binary.SubscribeBinaryTransactionsResponse.created_at:type_name -> google.protobuf.Timestamp
	4, // 3: shreder_binary.SubscribeUpdateBinaryTransaction.transaction:type_name -> shreder_binary.BinaryTransaction
	3, // 4: shreder_binary.SubscribeBinaryTransactionsRequest.TransactionsEntry.value:type_name -> shreder_binary.SubscribeRequestFilterBinaryTransactions
	0, // 5: shreder_binary.ShrederBinaryService.SubscribeBinaryTransactions:input_type -> shreder_binary.SubscribeBinaryTransactionsRequest
	1, // 6: shreder_binary.ShrederBinaryService.SubscribeBinaryTransactions:output_type -> shreder_binary.SubscribeBinaryTransactionsResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_shreder_binary_proto_init() }
func file_shreder_binary_proto_init() {
	if File_shreder_binary_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shreder_binary_proto_rawDesc), len(file_shreder_binary_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shreder_binary_proto_goTypes,
		DependencyIndexes: file_shreder_binary_proto_depIdxs,
		MessageInfos:      file_shreder_binary_proto_msgTypes,
	}.Build()
	File_shreder_binary_proto = out.File
	file_shreder_binary_proto_goTypes = nil
	file_shreder_binary_proto_depIdxs = nil
}
