// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.4
// source: shreder_binary.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShrederBinaryService_SubscribeBinaryTransactions_FullMethodName = "/shreder_binary.ShrederBinaryService/SubscribeBinaryTransactions"
)

// ShrederBinaryServiceClient is the client API for ShrederBinaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShrederBinaryServiceClient interface {
	SubscribeBinaryTransactions(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeBinaryTransactionsRequest, SubscribeBinaryTransactionsResponse], error)
}

type shrederBinaryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShrederBinaryServiceClient(cc grpc.ClientConnInterface) ShrederBinaryServiceClient {
	return &shrederBinaryServiceClient{cc}
}

func (c *shrederBinaryServiceClient) SubscribeBinaryTransactions(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SubscribeBinaryTransactionsRequest, SubscribeBinaryTransactionsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShrederBinaryService_ServiceDesc.Streams[0], ShrederBinaryService_SubscribeBinaryTransactions_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeBinaryTransactionsRequest, SubscribeBinaryTransactionsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShrederBinaryService_SubscribeBinaryTransactionsClient = grpc.BidiStreamingClient[SubscribeBinaryTransactionsRequest, SubscribeBinaryTransactionsResponse]

// ShrederBinaryServiceServer is the server API for ShrederBinaryService service.
// All implementations must embed UnimplementedShrederBinaryServiceServer
// for forward compatibility.
type ShrederBinaryServiceServer interface {
	SubscribeBinaryTransactions(grpc.BidiStreamingServer[SubscribeBinaryTransactionsRequest, SubscribeBinaryTransactionsResponse]) error
	mustEmbedUnimplementedShrederBinaryServiceServer()
}

// UnimplementedShrederBinaryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShrederBinaryServiceServer struct{}

func (UnimplementedShrederBinaryServiceServer) SubscribeBinaryTransactions(grpc.BidiStreamingServer[SubscribeBinaryTransactionsRequest, SubscribeBinaryTransactionsResponse]) error {
	return status.Error(codes.Unimplemented, "method SubscribeBinaryTransactions not implemented")
}
func (UnimplementedShrederBinaryServiceServer) mustEmbedUnimplementedShrederBinaryServiceServer() {}
func (UnimplementedShrederBinaryServiceServer) testEmbeddedByValue()                              {}

// UnsafeShrederBinaryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShrederBinaryServiceServer will
// result in compilation errors.
type UnsafeShrederBinaryServiceServer interface {
	mustEmbedUnimplementedShrederBinaryServiceServer()
}

func RegisterShrederBinaryServiceServer(s grpc.ServiceRegistrar, srv ShrederBinaryServiceServer) {
	// If the following call panics, it indicates UnimplementedShrederBinaryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShrederBinaryService_ServiceDesc, srv)
}

func _ShrederBinaryService_SubscribeBinaryTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShrederBinaryServiceServer).SubscribeBinaryTransactions(&grpc.GenericServerStream[SubscribeBinaryTransactionsRequest, SubscribeBinaryTransactionsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShrederBinaryService_SubscribeBinaryTransactionsServer = grpc.BidiStreamingServer[SubscribeBinaryTransactionsRequest, SubscribeBinaryTransactionsResponse]

// ShrederBinaryService_ServiceDesc is the grpc.ServiceDesc for ShrederBinaryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShrederBinaryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shreder_binary.ShrederBinaryService",
	HandlerType: (*ShrederBinaryServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeBinaryTransactions",
			Handler:       _ShrederBinaryService_SubscribeBinaryTransactions_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "shreder_binary.proto",
}
